-- Payment provenance is explicit per expense.  Historical rows are left
-- untouched because dates, revenue timing and FIFO do not prove which fund
-- paid an expense.  Users may populate funding_financial_account_id through
-- the expense API when the source is known.
-- This migration is intentionally a no-op.
