export const DOMAIN_PACKAGE = "@naai-erp/domain" as const;
export {
  validateCustomerReceipt,
  type CustomerReceiptAllocationInput,
} from "./customer-receipts.js";
export {
  validateFreelancePayable,
  validateFreelancePayment,
} from "./project-freelance-payables.js";
export {
  PORTABLE_DATA_PACKAGE_SCHEMA_VERSION,
  assertPortableRowOperation,
  assertPortableInventoryComplete,
  createPortableDataPackageManifest,
  hashPortableRows,
  packageHashForInventory,
  type PortableDataPackageManifest,
  type PortableRowOperation,
  type PortableSheetInventory,
} from "./portable-data-package.js";

export type OrganizationScoped = Readonly<{
  organizationId: string;
}>;

export { type AuditActorType, type AuditEvent } from "./audit.js";
export {
  PARTY_ROLES,
  PROJECT_STATES,
  assertProjectAcceptsAllocation,
  createContract,
  createMilestone,
  createParty,
  createProject,
  mergeParty,
  transitionProject,
  type Contract,
  type ContractType,
  type Milestone,
  type Party,
  type PartyRole,
  type PartyStatus,
  type Project,
  type ProjectState,
} from "./commercial.js";
export {
  ACCOUNT_ROOT_TYPES,
  TAX_KINDS,
  assertNonOverlappingVersions,
  assertValidAccountParent,
  createAccount,
  createStatutoryAccountMapping,
  createTaxCodeVersion,
  resolveEffectiveVersion,
  updateAccount,
  type Account,
  type AccountRootType,
  type StatutoryAccountMapping,
  type StatutoryFramework,
  type TaxCodeVersion,
  type TaxKind,
  type TaxReviewState,
} from "./chart-of-accounts.js";
export { ROLES, hasRole, type AuthorizationContext, type Role } from "./authorization.js";
export { assertSameOrganization, organizationId, type OrganizationId } from "./organization.js";
export {
  DIMENSION_KINDS,
  createDimensionRule,
  createDimensionValue,
  createDefaultMapping,
  validateAllocations,
  validateAmountAllocations,
  validateRequiredDimensions,
  type Allocation,
  type AmountAllocation,
  type DefaultMapping,
  type DimensionKind,
  type DimensionRule,
  type DimensionValue,
} from "./dimensions.js";
export {
  FISCAL_PERIOD_STATES,
  createCalendarYearPeriods,
  createExchangeRate,
  createMembership,
  createOrganization,
  currencyCode,
  transitionFiscalPeriod,
  type CurrencyCode,
  type ExchangeRate,
  type FiscalPeriod,
  type FiscalPeriodState,
  type Organization,
  type OrganizationMembership,
} from "./organization-setup.js";
export {
  JOURNAL_STATES,
  approveJournal,
  assertJournalBalanced,
  createDraftJournal,
  journalTotals,
  postJournal,
  reverseJournal,
  type JournalDimensions,
  type JournalEntry,
  type JournalLine,
  type JournalState,
  type JournalTotals,
} from "./journal.js";
export {
  POSTING_DIMENSIONS,
  assertManualJournalAllowed,
  createPostingRule,
  mapDocumentToJournalDraft,
  selectPostingRule,
  type AppliedPostingRule,
  type PostingDimension,
  type PostingDraftResult,
  type PostingRule,
  type PostingSourceLine,
  type ProtectedManualAccount,
} from "./posting-rules.js";
export {
  approveAccountingWorkflow,
  createAccountingWorkflow,
  createReplacementWorkflow,
  postAccountingWorkflow,
  reverseAccountingWorkflow,
  type AccountingWorkflow,
  type MakerCheckerPolicy,
  type WorkflowAuditAction,
  type WorkflowAuditEvent,
} from "./accounting-workflow.js";
export {
  assertPaymentSettlementAllowed,
  assertPostingAllowed,
  createFiscalPeriodWorkflow,
  findFiscalPeriod,
  lockFiscalPeriod,
  reopenFiscalPeriod,
  type FiscalPeriodEvent,
  type FiscalPeriodEventAction,
  type FiscalPeriodWorkflow,
  type ReopenPolicy,
} from "./fiscal-period-workflow.js";
export {
  buildGeneralLedger,
  buildTrialBalance,
  validateOpeningBalances,
  type GeneralLedger,
  type GeneralLedgerEntry,
  type LedgerDrilldown,
  type LedgerJournalRecord,
  type OpeningBalanceLine,
  type TrialBalance,
  type TrialBalanceRow,
  type ValidatedOpeningBalances,
} from "./ledger-reports.js";
export {
  createCreditNote,
  createPurchaseInvoice,
  createSalesInvoice,
  generateCreditNoteJournalDraft,
  generatePurchaseInvoiceJournalDraft,
  generateSalesInvoiceJournalDraft,
  recordPurchaseInvoicePayment,
  recordSalesInvoicePayment,
  transitionPurchaseInvoice,
  transitionSalesInvoice,
  type CreditNote,
  type DocumentAllocation,
  type InvoiceLine,
  type PaymentTerms,
  type PurchaseInvoice,
  type PurchaseInvoiceState,
  type SalesInvoice,
  type SalesInvoiceState,
} from "./documents.js";
export {
  EXPENSE_CLASSES,
  createExpense,
  generateExpenseBookingJournalDraft,
  generateReimbursementPaymentJournalDraft,
  reviewExpenseAxis,
  transitionExpense,
  updateExpenseEvidence,
  type AccountingTreatment,
  type Expense,
  type ExpenseClass,
  type ExpenseEvidenceFlags,
  type ExpenseReview,
  type ExpenseReviewAxis,
  type ExpenseReviewState,
  type ExpenseState,
} from "./expenses.js";
export {
  EVIDENCE_MEDIA_TYPES,
  detectEvidenceMediaType,
  nextEvidenceVersion,
  reviewEvidence,
  validateEvidenceUpload,
  type EvidenceMediaType,
  type EvidenceReviewState,
  type EvidenceStatus,
} from "./evidence.js";
export {
  assertSupportedOutboundEventVersion,
  beginOutboundDelivery,
  calculateOutboundFailureDecision,
  completeOutboundDelivery,
  createOutboundDelivery,
  createOutboundEvent,
  failOutboundDelivery,
  replayDeadLetter,
  type JsonObject,
  type JsonArray,
  type JsonPrimitive,
  type JsonValue,
  type OutboundBackoffPolicy,
  type OutboundDelivery,
  type OutboundDeliveryState,
  type OutboundEventContract,
  type OutboundFailureDecision,
} from "./outbound-events.js";
export {
  INBOUND_REPLAY_WINDOW_SECONDS,
  INBOUND_SCHEMA_VERSION,
  inboundRetryDelaySeconds,
  validateInboundEnvelope,
  validateInboundTimestamp,
  type InboundEnvelope,
} from "./inbound-webhooks.js";
export {
  BANK_ACCOUNT_KINDS,
  BANK_TRANSACTION_STATES,
  appendBankTransactionNormalization,
  bankTransactionSourceKey,
  buildBankTransactionFingerprintMaterial,
  createBankAccount,
  createBankTransaction,
  createBankTransactionNormalization,
  deactivateBankAccount,
  transitionBankTransaction,
  type BankAccount,
  type BankAccountKind,
  type BankAccountStatus,
  type BankJsonArray,
  type BankJsonObject,
  type BankJsonPrimitive,
  type BankJsonValue,
  type BankRawTransaction,
  type BankTransaction,
  type BankTransactionNormalization,
  type BankTransactionState,
} from "./banking.js";
export {
  RECONCILIATION_TARGET_KINDS,
  appendReconciliationAttempt,
  authorizeUnreconcile,
  bankStateAfterAuthorizedUnreconcile,
  buildReconciliationJournalLines,
  createMatchedReconciliation,
  decideAutoMatch,
  reconcilePayment,
  scoreReconciliationCandidate,
  type AutoMatchDecision,
  type CandidateScore,
  type MatchingPolicy,
  type PaymentDirection,
  type PaymentReconciliation,
  type ReconciliationAdjustment,
  type ReconciliationAdjustmentKind,
  type ReconciliationAllocation,
  type ReconciliationAttempt,
  type ReconciliationAttemptState,
  type ReconciliationCandidate,
  type ReconciliationJournalLine,
  type ReconciliationTargetKind,
  type ReconciliationTransactionView,
} from "./reconciliation.js";
export {
  authorizeUnmatchInternalTransfer,
  buildInternalTransferJournalPlan,
  createInternalTransfer,
  decideTransferCandidate,
  matchInternalTransfer,
  recordInternalTransferPosting,
  scoreTransferCandidate,
  type InternalTransfer,
  type InternalTransferAttempt,
  type InternalTransferFee,
  type InternalTransferState,
  type OwnedTransferTransaction,
  type TransferAuditEvent,
  type TransferCandidateDecision,
  type TransferCandidatePolicy,
  type TransferCandidateScore,
  type TransferJournalDraft,
  type TransferJournalLine,
  type TransferLeg,
  type TransferLegRole,
} from "./internal-transfers.js";
export {
  AGING_BUCKETS,
  UnsupportedAgingFxError,
  buildAgingReport,
  classifyAgingBucket,
  deriveAgingPaymentStatus,
  type AgingBalanceKind,
  type AgingBucket,
  type AgingControlBalance,
  type AgingControlTie,
  type AgingMovement,
  type AgingMovementState,
  type AgingPaymentStatus,
  type AgingReport,
  type AgingReportItem,
  type AgingSide,
  type AgingSourceItem,
} from "./aging.js";
export {
  BANK_STATEMENT_SESSION_STATES,
  STATEMENT_CONTROL_STATUSES,
  STATEMENT_TRANSACTION_DISPOSITIONS,
  approveStatementSuspenseException,
  closeBankStatementSession,
  createBankStatementSession,
  createStatementSuspenseException,
  rejectStatementSuspenseException,
  resolveStatementSuspenseException,
  reviewBankStatementSession,
  statementCloseBlockers,
  type BankStatementControlEvent,
  type BankStatementSession,
  type BankStatementSessionState,
  type StatementControlStatus,
  type StatementSuspenseException,
  type StatementTransactionControl,
  type StatementTransactionDisposition,
  type SuspenseExceptionState,
} from "./banking-controls.js";
export {
  approveProjectBudgetVersion,
  approveScopeChange,
  assertBudgetVersionSequence,
  createProjectBudgetVersion,
  createScopeChange,
  rejectProjectBudgetVersion,
  rejectScopeChange,
  submitProjectBudgetVersion,
  submitScopeChange,
  supersedeProjectBudgetVersion,
  type ProjectBudgetCategory,
  type ProjectBudgetKind,
  type ProjectBudgetLine,
  type ProjectBudgetState,
  type ProjectBudgetVersion,
  type ScopeChange,
  type ScopeChangeState,
} from "./project-budgets.js";
export {
  acceptMilestone,
  approveRevenueRecognitionEvent,
  approveRevenueRecognitionPolicy,
  buildProjectRevenueAxes,
  buildRecognitionJournalLines,
  createMilestoneAcceptance,
  createRevenueRecognitionEvent,
  createRevenueRecognitionPolicy,
  postRevenueRecognitionEvent,
  resolveRevenueRecognitionPolicy,
  retireRevenueRecognitionPolicy,
  reverseRevenueRecognitionEvent,
  reviewMilestoneAcceptance,
  submitRevenueRecognitionEvent,
  type MilestoneAcceptance,
  type MilestoneAcceptanceState,
  type ProjectRevenueAxes,
  type ProjectRevenueAxisMovement,
  type RecognitionEventState,
  type RecognitionJournalLine,
  type RecognitionMethod,
  type RecognitionPolicyState,
  type RevenueRecognitionEvent,
  type RevenueRecognitionPolicy,
} from "./revenue-recognition.js";
export {
  buildProjectProfitability,
  profitabilityRatioBps,
  type ProjectProfitability,
  type ProjectProfitabilityConfidenceCode,
  type ProjectProfitabilityConfidenceFlag,
  type ProjectProfitabilityDrilldown,
  type ProjectProfitabilityInput,
} from "./project-profitability.js";
export {
  ACTUAL_BASES,
  FORECAST_SCENARIOS,
  TARGET_PERIOD_KINDS,
  assertForecastVersionSequence,
  assertRevenueTargetVersionSequence,
  createForecastVersion,
  createRevenueTargetVersion,
  publishForecastVersion,
  publishRevenueTargetVersion,
  supersedeForecastVersion,
  supersedeRevenueTargetVersion,
  type ActualBasis,
  type ForecastScenario,
  type ForecastSnapshotKind,
  type ForecastVersion,
  type PlanningDimensions,
  type PlanningVersionState,
  type RevenueTargetVersion,
  type TargetPeriodKind,
} from "./planning.js";
export {
  FORECAST_COMPONENT_KINDS,
  FORECAST_COMPONENT_SECTIONS,
  FORECAST_SOURCE_TYPES,
  assertForecastComponentMutable,
  assertForecastCompositionPublishable,
  assertNoForecastSourceDoubleCount,
  buildForecastComposition,
  createForecastComponent,
  excludeForecastComponent,
  reviewForecastManualAdjustment,
  weightedForecastComponentMinor,
  type ForecastComponent,
  type ForecastComponentDirection,
  type ForecastComponentKind,
  type ForecastComponentReviewState,
  type ForecastComponentSection,
  type ForecastComponentState,
  type ForecastComposition,
  type ForecastCompositionContext,
  type ForecastSourceIdentity,
  type ForecastSourceSnapshot,
  type ForecastSourceType,
} from "./forecast-composition.js";
export {
  PERFORMANCE_COMPARISON_FORMULA_VERSION,
  PERFORMANCE_NULL_POLICY_VERSION,
  PERFORMANCE_PRORATION_FORMULA_VERSION,
  PERFORMANCE_WINDOW_FORMULA_VERSION,
  buildPerformanceComparison,
  prorateTargetInclusive,
  type PerformanceAmount,
  type PerformanceAmountStatus,
  type PerformanceComparison,
  type PerformanceComparisonBasis,
  type PerformanceComparisonInput,
  type PerformanceComparisonLine,
  type PerformanceConfidenceFlag,
  type PerformancePeriod,
  type PerformancePeriodBasis,
  type PerformancePeriodKind,
  type PerformanceResultStatus,
  type PerformanceWindow,
} from "./performance-comparisons.js";
export {
  BALANCE_SHEET_FORMULA_VERSION,
  DIRECT_CASH_FLOW_FORMULA_VERSION,
  FINANCIAL_LEDGER_CONTROL_VERSION,
  PROFIT_AND_LOSS_FORMULA_VERSION,
  buildBalanceSheet,
  buildDirectCashFlow,
  buildProfitAndLoss,
  type BalanceSheet,
  type CashFlowJournal,
  type CashFlowSection,
  type CashFlowSourceKind,
  type DirectCashFlow,
  type FinancialControl,
  type FinancialLedgerLine,
  type FinancialReportStatus,
  type FinancialRootType,
  type FinancialStatementRow,
  type LedgerCutoff,
  type ProfitAndLoss,
  type ProfitAndLossSection,
} from "./financial-statements.js";
export {
  TAX_EXPENSE_REVIEW_FORMULA_VERSION,
  VAT_RECONCILIATION_FORMULA_VERSION,
  buildTaxExpenseReview,
  buildVatReconciliation,
  type TaxExpenseReview,
  type TaxExpenseReviewItem,
  type TaxReportStatus,
  type TaxEligibilityReviewState,
  type VatReconciliation,
  type VatReconciliationPolicy,
  type VatSourceItem,
} from "./tax-reconciliation.js";
export {
  EQUITY_CONSUMED_FORMULA_VERSION,
  EQUITY_ROLL_FORWARD_CONTROL_VERSION,
  EXECUTIVE_METRICS_FORMULA_VERSION,
  OPERATING_BURN_FORMULA_VERSION,
  PROFITABILITY_RATIO_FORMULA_VERSION,
  PURPOSE_SPECIFIC_ROI_FORMULA_VERSION,
  RETURN_RATIO_FORMULA_VERSION,
  RUNWAY_FORMULA_VERSION,
  buildExecutiveMetrics,
  type ExecutiveDimensions,
  type ExecutiveMetricPeriod,
  type ExecutiveMetricStatus,
  type ExecutiveMetrics,
  type ExecutiveMetricsInput,
  type ExecutiveRatio,
  type ExecutiveSourceBoundary,
  type PurposeSpecificRoi,
  type PurposeSpecificRoiInput,
} from "./executive-metrics.js";
export {
  ACCOUNTANT_REPORT_KINDS,
  REPORT_SNAPSHOT_HASH_ALGORITHM,
  REPORT_SNAPSHOT_SCHEMA_VERSION,
  assertSnapshotFinal,
  canonicalJson,
  createReportSnapshot,
  sha256Hex,
  snapshotReadiness,
  verifySnapshotReproduction,
  type AccountantReportKind,
  type CanonicalJsonValue,
  type ReportSnapshot,
  type SnapshotLedgerCutoff,
  type SnapshotMapping,
  type SnapshotMappingStatus,
  type SnapshotReadiness,
  type SnapshotUnresolvedItem,
} from "./report-snapshots.js";
export {
  ACCOUNTANT_EXPORT_SCHEMA_VERSION,
  createAccountantExportManifest,
  createAccountantWorkbook,
  workbookSheetToCsv,
  type AccountantExportManifest,
  type AccountantWorkbook,
  type WorkbookCell,
  type WorkbookCellValue,
  type WorkbookSheet,
} from "./accountant-exports.js";
export {
  SERVICE_BUSINESS_METRICS_FORMULA_VERSION,
  buildServiceBusinessMetrics,
  type ClientPerformanceInput,
  type ContractBacklogInput,
  type ProjectDeliveryInput,
  type RevenueMixInput,
  type ServiceBusinessConfidenceCode,
  type ServiceBusinessConfidenceFlag,
  type ServiceBusinessMetrics,
  type ServiceBusinessMetricsInput,
} from "./service-business-metrics.js";
export {
  SUBSCRIPTION_RECURRENCE_FREQUENCIES,
  assertExactMoney,
  assertRecurrence,
  buildSubscriptionSchedule,
  servicePlanCodeFromName,
  subscriptionNextActions,
  transitionSubscription,
  type SubscriptionAction,
  type SubscriptionLifecycle,
  type SubscriptionRecurrence,
  type SubscriptionScheduleInput,
  type SubscriptionSchedulePeriod,
} from "./customer-service-subscriptions.js";
