export const DOMAIN_PACKAGE = "@naai-erp/domain" as const;

export type OrganizationScoped = Readonly<{
  organizationId: string;
}>;

export { type AuditActorType, type AuditEvent } from "./audit.js";
export {
  PARTY_ROLES,
  PROJECT_STATES,
  assertProjectAcceptsAllocation,
  createContract,
  createMilestone,
  createParty,
  createProject,
  mergeParty,
  transitionProject,
  type Contract,
  type ContractType,
  type Milestone,
  type Party,
  type PartyRole,
  type PartyStatus,
  type Project,
  type ProjectState,
} from "./commercial.js";
export {
  ACCOUNT_ROOT_TYPES,
  TAX_KINDS,
  assertNonOverlappingVersions,
  assertValidAccountParent,
  createAccount,
  createStatutoryAccountMapping,
  createTaxCodeVersion,
  resolveEffectiveVersion,
  updateAccount,
  type Account,
  type AccountRootType,
  type StatutoryAccountMapping,
  type StatutoryFramework,
  type TaxCodeVersion,
  type TaxKind,
  type TaxReviewState,
} from "./chart-of-accounts.js";
export { ROLES, hasRole, type AuthorizationContext, type Role } from "./authorization.js";
export { assertSameOrganization, organizationId, type OrganizationId } from "./organization.js";
export {
  DIMENSION_KINDS,
  createDimensionRule,
  createDimensionValue,
  createDefaultMapping,
  validateAllocations,
  validateAmountAllocations,
  validateRequiredDimensions,
  type Allocation,
  type AmountAllocation,
  type DefaultMapping,
  type DimensionKind,
  type DimensionRule,
  type DimensionValue,
} from "./dimensions.js";
export {
  FISCAL_PERIOD_STATES,
  createCalendarYearPeriods,
  createExchangeRate,
  createMembership,
  createOrganization,
  currencyCode,
  transitionFiscalPeriod,
  type CurrencyCode,
  type ExchangeRate,
  type FiscalPeriod,
  type FiscalPeriodState,
  type Organization,
  type OrganizationMembership,
} from "./organization-setup.js";
export {
  JOURNAL_STATES,
  approveJournal,
  assertJournalBalanced,
  createDraftJournal,
  journalTotals,
  postJournal,
  reverseJournal,
  type JournalDimensions,
  type JournalEntry,
  type JournalLine,
  type JournalState,
  type JournalTotals,
} from "./journal.js";
export {
  POSTING_DIMENSIONS,
  assertManualJournalAllowed,
  createPostingRule,
  mapDocumentToJournalDraft,
  selectPostingRule,
  type AppliedPostingRule,
  type PostingDimension,
  type PostingDraftResult,
  type PostingRule,
  type PostingSourceLine,
  type ProtectedManualAccount,
} from "./posting-rules.js";
export {
  approveAccountingWorkflow,
  createAccountingWorkflow,
  createReplacementWorkflow,
  postAccountingWorkflow,
  reverseAccountingWorkflow,
  type AccountingWorkflow,
  type MakerCheckerPolicy,
  type WorkflowAuditAction,
  type WorkflowAuditEvent,
} from "./accounting-workflow.js";
export {
  assertPaymentSettlementAllowed,
  assertPostingAllowed,
  createFiscalPeriodWorkflow,
  findFiscalPeriod,
  lockFiscalPeriod,
  reopenFiscalPeriod,
  type FiscalPeriodEvent,
  type FiscalPeriodEventAction,
  type FiscalPeriodWorkflow,
  type ReopenPolicy,
} from "./fiscal-period-workflow.js";
export {
  buildGeneralLedger,
  buildTrialBalance,
  validateOpeningBalances,
  type GeneralLedger,
  type GeneralLedgerEntry,
  type LedgerDrilldown,
  type LedgerJournalRecord,
  type OpeningBalanceLine,
  type TrialBalance,
  type TrialBalanceRow,
  type ValidatedOpeningBalances,
} from "./ledger-reports.js";
export {
  createCreditNote,
  createPurchaseInvoice,
  createSalesInvoice,
  generateCreditNoteJournalDraft,
  generatePurchaseInvoiceJournalDraft,
  generateSalesInvoiceJournalDraft,
  recordPurchaseInvoicePayment,
  recordSalesInvoicePayment,
  transitionPurchaseInvoice,
  transitionSalesInvoice,
  type CreditNote,
  type DocumentAllocation,
  type InvoiceLine,
  type PaymentTerms,
  type PurchaseInvoice,
  type PurchaseInvoiceState,
  type SalesInvoice,
  type SalesInvoiceState,
} from "./documents.js";
export {
  EXPENSE_CLASSES,
  createExpense,
  generateExpenseBookingJournalDraft,
  generateReimbursementPaymentJournalDraft,
  reviewExpenseAxis,
  transitionExpense,
  updateExpenseEvidence,
  type AccountingTreatment,
  type Expense,
  type ExpenseClass,
  type ExpenseEvidenceFlags,
  type ExpenseReview,
  type ExpenseReviewAxis,
  type ExpenseReviewState,
  type ExpenseState,
} from "./expenses.js";
export {
  EVIDENCE_MEDIA_TYPES,
  detectEvidenceMediaType,
  nextEvidenceVersion,
  reviewEvidence,
  validateEvidenceUpload,
  type EvidenceMediaType,
  type EvidenceReviewState,
  type EvidenceStatus,
} from "./evidence.js";
export {
  assertSupportedOutboundEventVersion,
  beginOutboundDelivery,
  calculateOutboundFailureDecision,
  completeOutboundDelivery,
  createOutboundDelivery,
  createOutboundEvent,
  failOutboundDelivery,
  replayDeadLetter,
  type JsonObject,
  type JsonArray,
  type JsonPrimitive,
  type JsonValue,
  type OutboundBackoffPolicy,
  type OutboundDelivery,
  type OutboundDeliveryState,
  type OutboundEventContract,
  type OutboundFailureDecision,
} from "./outbound-events.js";
export {
  INBOUND_REPLAY_WINDOW_SECONDS,
  INBOUND_SCHEMA_VERSION,
  inboundRetryDelaySeconds,
  validateInboundEnvelope,
  validateInboundTimestamp,
  type InboundEnvelope,
} from "./inbound-webhooks.js";
export {
  BANK_ACCOUNT_KINDS,
  BANK_TRANSACTION_STATES,
  appendBankTransactionNormalization,
  bankTransactionSourceKey,
  buildBankTransactionFingerprintMaterial,
  createBankAccount,
  createBankTransaction,
  createBankTransactionNormalization,
  deactivateBankAccount,
  transitionBankTransaction,
  type BankAccount,
  type BankAccountKind,
  type BankAccountStatus,
  type BankJsonArray,
  type BankJsonObject,
  type BankJsonPrimitive,
  type BankJsonValue,
  type BankRawTransaction,
  type BankTransaction,
  type BankTransactionNormalization,
  type BankTransactionState,
} from "./banking.js";
export {
  RECONCILIATION_TARGET_KINDS,
  appendReconciliationAttempt,
  authorizeUnreconcile,
  bankStateAfterAuthorizedUnreconcile,
  buildReconciliationJournalLines,
  createMatchedReconciliation,
  decideAutoMatch,
  reconcilePayment,
  scoreReconciliationCandidate,
  type AutoMatchDecision,
  type CandidateScore,
  type MatchingPolicy,
  type PaymentDirection,
  type PaymentReconciliation,
  type ReconciliationAdjustment,
  type ReconciliationAdjustmentKind,
  type ReconciliationAllocation,
  type ReconciliationAttempt,
  type ReconciliationAttemptState,
  type ReconciliationCandidate,
  type ReconciliationJournalLine,
  type ReconciliationTargetKind,
  type ReconciliationTransactionView,
} from "./reconciliation.js";
export {
  authorizeUnmatchInternalTransfer,
  buildInternalTransferJournalPlan,
  createInternalTransfer,
  decideTransferCandidate,
  matchInternalTransfer,
  recordInternalTransferPosting,
  scoreTransferCandidate,
  type InternalTransfer,
  type InternalTransferAttempt,
  type InternalTransferFee,
  type InternalTransferState,
  type OwnedTransferTransaction,
  type TransferAuditEvent,
  type TransferCandidateDecision,
  type TransferCandidatePolicy,
  type TransferCandidateScore,
  type TransferJournalDraft,
  type TransferJournalLine,
  type TransferLeg,
  type TransferLegRole,
} from "./internal-transfers.js";
export {
  AGING_BUCKETS,
  UnsupportedAgingFxError,
  buildAgingReport,
  classifyAgingBucket,
  deriveAgingPaymentStatus,
  type AgingBalanceKind,
  type AgingBucket,
  type AgingControlBalance,
  type AgingControlTie,
  type AgingMovement,
  type AgingMovementState,
  type AgingPaymentStatus,
  type AgingReport,
  type AgingReportItem,
  type AgingSide,
  type AgingSourceItem,
} from "./aging.js";
export {
  BANK_STATEMENT_SESSION_STATES,
  STATEMENT_CONTROL_STATUSES,
  STATEMENT_TRANSACTION_DISPOSITIONS,
  approveStatementSuspenseException,
  closeBankStatementSession,
  createBankStatementSession,
  createStatementSuspenseException,
  rejectStatementSuspenseException,
  resolveStatementSuspenseException,
  reviewBankStatementSession,
  statementCloseBlockers,
  type BankStatementControlEvent,
  type BankStatementSession,
  type BankStatementSessionState,
  type StatementControlStatus,
  type StatementSuspenseException,
  type StatementTransactionControl,
  type StatementTransactionDisposition,
  type SuspenseExceptionState,
} from "./banking-controls.js";
export {
  TIMESHEET_STATES,
  approveLaborCostRate,
  approveTimeAdjustment,
  approveTimesheet,
  assertNoTimeOverlap,
  assertNonOverlappingCostRates,
  buildTimeCapacitySummary,
  calculateAppliedLaborCost,
  createLaborCostRate,
  createTimeAdjustment,
  createTimesheet,
  createWorkerCapacityVersion,
  createWorkforceProfile,
  deactivateWorkforceProfile,
  lockTimesheet,
  markTimesheetBilled,
  rejectTimesheet,
  resolveEffectiveCostRate,
  resolveWorkerCapacity,
  retireLaborCostRate,
  reviseRejectedTimesheet,
  submitTimeAdjustment,
  submitTimesheet,
  type AppliedLaborCost,
  type BillingClassification,
  type LaborCostBasis,
  type LaborCostRateState,
  type LaborCostRateVersion,
  type TimeAdjustment,
  type TimeCapacitySummary,
  type TimeEntry,
  type TimeEntryMode,
  type Timesheet,
  type TimesheetEvent,
  type TimesheetState,
  type WorkClassification,
  type WorkforceProfile,
  type WorkerCapacityVersion,
} from "./time.js";
export {
  approveDirectCostAllocation,
  assertSourceNotDirectAndOverhead,
  createDirectCostAllocation,
  createProjectCostSource,
  createSourceLinkedProjectCost,
  materializeDirectProjectCosts,
  postDirectCostAllocation,
  reverseDirectCostAllocation,
  submitDirectCostAllocation,
  type CostAllocationDisposition,
  type DirectCostAllocation,
  type DirectCostAllocationEvent,
  type DirectCostAllocationState,
  type DirectCostSplit,
  type ProjectCostBasis,
  type ProjectCostClass,
  type ProjectCostItem,
  type ProjectCostSource,
  type ProjectCostSourceType,
} from "./project-costs.js";
export {
  approveProjectBudgetVersion,
  approveScopeChange,
  assertBudgetVersionSequence,
  createProjectBudgetVersion,
  createScopeChange,
  rejectProjectBudgetVersion,
  rejectScopeChange,
  submitProjectBudgetVersion,
  submitScopeChange,
  supersedeProjectBudgetVersion,
  type ProjectBudgetCategory,
  type ProjectBudgetKind,
  type ProjectBudgetLine,
  type ProjectBudgetState,
  type ProjectBudgetVersion,
  type ScopeChange,
  type ScopeChangeState,
} from "./project-budgets.js";
export {
  acceptMilestone,
  approveRevenueRecognitionEvent,
  approveRevenueRecognitionPolicy,
  buildProjectRevenueAxes,
  buildRecognitionJournalLines,
  createMilestoneAcceptance,
  createRevenueRecognitionEvent,
  createRevenueRecognitionPolicy,
  postRevenueRecognitionEvent,
  resolveRevenueRecognitionPolicy,
  retireRevenueRecognitionPolicy,
  reverseRevenueRecognitionEvent,
  reviewMilestoneAcceptance,
  submitRevenueRecognitionEvent,
  type MilestoneAcceptance,
  type MilestoneAcceptanceState,
  type ProjectRevenueAxes,
  type ProjectRevenueAxisMovement,
  type RecognitionEventState,
  type RecognitionJournalLine,
  type RecognitionMethod,
  type RecognitionPolicyState,
  type RevenueRecognitionEvent,
  type RevenueRecognitionPolicy,
} from "./revenue-recognition.js";
