import { Catch, type ArgumentsHost, type ExceptionFilter } from "@nestjs/common";
import type { FastifyReply } from "fastify";

const STATUS_BY_CODE: Readonly<Record<string, number>> = {
  AUTH_REQUIRED: 401,
  FORBIDDEN: 403,
  RESOURCE_NOT_FOUND: 404,
  VALIDATION_FAILED: 400,
  IDEMPOTENCY_KEY_REQUIRED: 400,
  "Idempotency key was reused with a different request": 409,
  "Resource version conflict": 409,
  IDEMPOTENCY_CONFLICT: 409,
  JOURNAL_ALREADY_POSTED: 409,
  INVALID_JOURNAL_STATE: 409,
  JOURNAL_UNBALANCED: 422,
  INVALID_POSTING_RULE: 422,
  JOURNAL_NOT_APPROVED: 409,
  MAKER_CHECKER_VIOLATION: 409,
  JOURNAL_ALREADY_REVERSED: 409,
  INVALID_PERIOD_TRANSITION: 409,
  FISCAL_PERIOD_NOT_FOUND: 422,
  FISCAL_PERIOD_AMBIGUOUS: 422,
  PERIOD_SOFT_LOCKED: 409,
  PERIOD_HARD_LOCKED: 409,
  OPENING_BALANCE_CONTROL_TOTAL_MISMATCH: 422,
  OPENING_BALANCE_SUBLEDGER_DETAIL_REQUIRED: 422,
  OPENING_BALANCE_ACCOUNT_INVALID: 422,
  DOCUMENT_ALLOCATION_INVALID: 422,
  DOCUMENT_ALLOCATION_MISMATCH: 422,
  DOCUMENT_CONTROL_TOTAL_MISMATCH: 422,
  INVALID_DOCUMENT_TRANSITION: 409,
  CREDIT_ORIGINAL_INVALID: 422,
  CREDIT_ORIGINAL_MISMATCH: 422,
  CREDIT_EXCEEDS_REMAINING: 409,
  CREDIT_ORIGINAL_LINE_REQUIRED: 422,
  CREDIT_ORIGINAL_LINE_INVALID: 422,
  PURCHASE_TAX_REVIEW_REQUIRED: 422,
  REIMBURSEMENT_EMPLOYEE_REQUIRED: 422,
  EXPENSE_ALLOCATION_INVALID: 422,
  EXPENSE_ALLOCATION_MISMATCH: 422,
  EXPENSE_CONTROL_TOTAL_MISMATCH: 422,
  VAT_EVIDENCE_REQUIRED: 422,
  ACCOUNTANT_OVERRIDE_REFERENCE_REQUIRED: 422,
  ELIGIBILITY_AMOUNT_INVALID: 422,
  EXPENSE_FINAL_IMMUTABLE: 409,
  INVALID_EXPENSE_TRANSITION: 409,
  EXPENSE_REVIEW_INCOMPLETE: 422,
  EXPENSE_EVIDENCE_INCOMPLETE: 422,
  EVIDENCE_EMPTY: 422,
  EVIDENCE_TOO_LARGE: 413,
  EVIDENCE_MEDIA_UNSUPPORTED: 415,
  EVIDENCE_MEDIA_MISMATCH: 415,
  EVIDENCE_XML_UNSAFE: 422,
  EVIDENCE_REVIEW_REASON_REQUIRED: 422,
  EVIDENCE_VERSION_NOT_ACTIVE: 409,
  EVIDENCE_DOWNLOAD_NOT_ALLOWED: 403,
  EVIDENCE_DOWNLOAD_TTL_INVALID: 422,
  EVIDENCE_CONCURRENT_REPLACEMENT: 409,
  WEBHOOK_SOURCE_UNAUTHORIZED: 401,
  WEBHOOK_AUTH_REQUIRED: 401,
  WEBHOOK_SIGNATURE_INVALID: 401,
  WEBHOOK_TIMESTAMP_INVALID: 401,
  WEBHOOK_TIMESTAMP_OUTSIDE_WINDOW: 401,
  WEBHOOK_EXTERNAL_ID_CONFLICT: 409,
  WEBHOOK_REPLAY_NOT_ALLOWED: 409,
  DELIVERY_LEASE_LOST: 409,
  REPLAY_NOT_ALLOWED: 409,
  REPLAY_REASON_REQUIRED: 422,
  VERSION_CONFLICT: 409,
  OUTBOUND_ENDPOINT_INVALID: 422,
};

@Catch()
export class ApiExceptionFilter implements ExceptionFilter {
  catch(exception: unknown, host: ArgumentsHost): void {
    const response = host.switchToHttp().getResponse<FastifyReply>();
    const message = exception instanceof Error ? exception.message : "INTERNAL_ERROR";
    const status = STATUS_BY_CODE[message] ?? 400;
    response.status(status).send({
      apiVersion: "v1",
      error: {
        code: message.replaceAll(" ", "_").toUpperCase(),
        message,
        retryable: status >= 500,
      },
    });
  }
}
