import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const migration = readFileSync(
  new URL("../../../db/migrations/0052_bound_generated_export_storage.sql", import.meta.url),
  "utf8",
);

describe("ERP-906 bounded generated export storage migration", () => {
  it("prunes only generated bytes while retaining export identity and metadata", () => {
    expect(migration).toContain(
      'ALTER TABLE "accountant_exports" ALTER COLUMN "content" DROP NOT NULL',
    );
    expect(migration).toContain(
      'ALTER TABLE "portable_data_packages" ALTER COLUMN "content" DROP NOT NULL',
    );
    expect(migration).toContain('ADD COLUMN "content_pruned_at"');
    expect(migration).not.toMatch(/DROP TABLE|TRUNCATE|DELETE FROM/i);
  });

  it("keeps accountant export history immutable except for one-way blob pruning", () => {
    expect(migration).toContain("OLD.content IS NOT NULL");
    expect(migration).toContain("NEW.content IS NULL");
    expect(migration).toContain("OLD.content_pruned_at IS NULL");
    expect(migration).toContain("NEW.content_pruned_at IS NOT NULL");
    expect(migration).toContain("accountant exports cannot be deleted");
  });
});
