export const DATABASE_PACKAGE = "@naai-erp/database" as const;

export {
  accountRootType,
  accountHierarchyEdges,
  accounts,
  exchangeRates,
  defaultMappingVersions,
  dimensionKind,
  dimensionRequirementVersions,
  dimensionValues,
  fiscalPeriods,
  fiscalPeriodState,
  fiscalYears,
  membershipRoles,
  organizationMemberships,
  organizations,
  role,
  schema,
  users,
  contractType,
  contracts,
  milestones,
  parties,
  partyBankAccounts,
  partyExternalReferences,
  partyMergeLinks,
  partyRole,
  partyRoles,
  partyStatus,
  projectState,
  projects,
  statutoryAccountMappings,
  statutoryFramework,
  taxCodeVersions,
  taxKind,
  taxReviewState,
} from "./schema.js";
